//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISSchedule_Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SISScheduleMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SISScheduleMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SISSchedule_Utilities.SISScheduleMessage", typeof(SISScheduleMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!! There is some error please Delete again. .
        /// </summary>
        public static string ProviderDeleteFaillure {
            get {
                return ResourceManager.GetString("ProviderDeleteFaillure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!! your information is Deleted sussessfully..
        /// </summary>
        public static string ProviderDeleteSucccess {
            get {
                return ResourceManager.GetString("ProviderDeleteSucccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops...Try again with appropriate information..
        /// </summary>
        public static string ProviderFailure {
            get {
                return ResourceManager.GetString("ProviderFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation!! Provider information is successfully submited..
        /// </summary>
        public static string ProviderSuccess {
            get {
                return ResourceManager.GetString("ProviderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!! There is some error please update again..
        /// </summary>
        public static string ProviderUpdateFailure {
            get {
                return ResourceManager.GetString("ProviderUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Provider information is sussessfully updated. .
        /// </summary>
        public static string ProviderUpdateSuccess {
            get {
                return ResourceManager.GetString("ProviderUpdateSuccess", resourceCulture);
            }
        }
    }
}
